### ISSUE TITLE
[Request][Fleet] Account for removal of default agent policy 

### ISSUE THREAD

**Issue by jen-huang** [elastic/observability-docs#1489]
## Description

Account for removal of default agent policy, as implemented in 8.1 via https://github.com/elastic/kibana/issues/108456.

At minimum this page:
https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html

## Collaboration

- The docs team will lead producing the content

**Contact Person:** @juliaElastic  

## Suggested Target Release

8.1

## Stakeholders

Fleet UI team

### Docs to update:

1. https://www.elastic.co/guide/en/fleet/current/add-a-fleet-server.html
Update Self managed tab: 
- add step to create Fleet Server policy (create button available on the form)
- update screenshot
- update elastic-agent install commands to remove -f flag (removed a while back)

2. https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html
Installation steps:
- add step to create Agent policy (create button available on the form)
- update screenshot
- remove references of default agent policy from text (there will be no default created from 8.1)
- update elastic-agent install commands to remove -f flag (removed a while back)

3. https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html
Self-managed example, Docker compose example:
- remove references of default policy from text
- add `--env FLEET_SERVER_POLICY_ID=fleet-server-policy` parameter
- link to the new page below on how to create agent policies with API or preconfiguration

4. https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html
- Add parameter in the manifest file:
```
- name: FLEET_SERVER_POLICY_ID
- value: fleet-server-policy
```
- add a link to the new page below on how to create agent policies
- update text about getting default policy, FLEET_ENROLLMENT_TOKEN should not be empty

5. https://www.elastic.co/guide/en/fleet/current/fleet-overview.html
- update screenshot at Elastic Agent policies, to show the new UI of Add integration
- Add a link about the info on how to create agent policies

6. https://www.elastic.co/guide/en/fleet/8.0/fleet-agent-proxy-support.html
- update Note about default policies, change it to saying that policies have to be created first.

7. https://www.elastic.co/guide/en/fleet/8.0/agent-policy.html
- remove Note about Default policy

8. Create a new page to summarize the steps to create agent policies without going to the UI:

Option 1.   Add agent policy with the API

  ```
  POST <kibana_host:port>/api/fleet/agent_policies?sys_monitoring=true
  
  {"name":"Agent policy 1","namespace":"default","monitoring_enabled":["logs","metrics"]}
  ```
   - `sys_monitoring`: enables system integration on the policy
   - `monitoring_enabled`: enables elastic agent monitoring

Option 2. Create agent policies with preconfiguration

  - Add preconfigured policies to kibana.yml config:
  - Example Fleet Server policy for Self-managed setup:
  ```
  xpack.fleet.packages:
    - name: fleet_server
      version: latest
  xpack.fleet.agentPolicies:
    - name: Fleet Server policy
      id: fleet-server-policy
      namespace: default
      package_policies:
        - name: fleet_server-1
          package:
            name: fleet_server
  ```
  - Example Agent policy for general use:
  ```
  xpack.fleet.packages:
    - name: system
      version: latest
    - name: elastic_agent
      version: latest
  xpack.fleet.agentPolicies:
    - name: Agent policy 1
      id: agent-policy-1
      namespace: default
      monitoring_enabled:
        - logs
        - metrics
      package_policies:
        - name: system-1
          id: default-system
          package:
            name: system
  ```

### Release Notes

Highlight the change that Default policy will not be available by default, and has to be created on UI/API or preconfiguration.
Highlight the change that for Self-managed, Default Fleet Server policy will not be available by default, and has to be created on UI/API or preconfiguration.
Elastic Cloud agent policy is not changed, will continue to be provided by default.
Add a link to the new doc page created above for creating agent policies.
