### ISSUE TITLE
[Synthetics] Document Lightweight monitors in Project Monitors

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2221]
## Description

https://github.com/elastic/synthetics/issues/542 added the ability to create Lightweight Project Monitors.

The current [Project Monitor Docs](https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html#synthetic-monitor-choose-project) don’t specifically mention only (previously) being for browser monitors, but maybe it should be mentioned here, that it can now be used for both browser and lightweight monitors.

I suspect the `Project monitors` tab of the [Configure monitor docs](https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html#monitor-use) should have the lightweight syntax included.

This works by including a `yml` file somewhere in the project folder, that includes monitor configurations:
```
heartbeat.monitors:
- type: http
  id: elastic-http
  name: Elastic HTTP check
  urls: ["https://elastic.co"]
  schedule: "@every 60s"
  tags: ["org:elastic"]
- type: tcp
  id: elastic-tcp
  name: Elastic TCP check
  hosts: ["elastic.co"]
  schedule: "@every 60s"
  tags: ["org:elastic"]
```

Note that there are some limitations when running lightweight monitors as project monitors.  Not all configuration options supported under a traditional `heartbeat.yml` are supported in project monitors.  If you attempt to `push` a project monitor with a configuration not supported, the push will fail with the error, for example:

```
✖ Error
   > Unsupported Heartbeat option: monitor([monitor name])
       The following Heartbeat options are not supported for http project monitors in 8.5.0: mode|ipv6|response.include_body_max_bytes. You monitor was not created or updated.
```

The most frequent a project monitor can run is every 60 seconds, so the following warning is given on lightweight pushes that have an invalid frequency configuration:

> :warning: lightweight monitors schedule < 1 minute resolution are not supported, will get reset to their nearest minute interval.
(this working will change)

If no schedule is defined, the default from the `synthetics.config.ts` will be used (as with browser project monitors).

## Collaboration

* The docs team will lead producing the content with support from @vigneshshanmugam 

## Suggested Target Release

* 8.5.0

## Stakeholders

@vigneshshanmugam 
@paulb-elastic 
@andrewvc
