### ISSUE TITLE
[Logs+] Align the Parse and organize logs docs with the Stream logs page

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#3398]
The dataset set in the Stream any log file page and does not match the examples in the Parse and organize logs page causing templates to not be applied. This causes frustration for users that are trying to move to the parsing page using their actual logs that they've ingested.

The code on the Parse and Filter pages should work with the code on the Stream page.

source: https://elastic.slack.com/archives/CEFAY0599/p1701451408635199

**Comment by bvader** [comment]
This needs to be corrected [here](https://www.elastic.co/guide/en/observability/8.11/logs-stream.html#logs-stream-example-config)

from

```
outputs:
  default:
    type: elasticsearch
    hosts: '<your-elasticsearch-endpoint>:<port>'
    api_key: 'your-api-key'
inputs:
  - id: your-log-id
    type: filestream
    streams:
      - id: your-log-stream-id
        data_stream.dataset: generic
        paths:
          - /var/log/your-logs.log
 ```

to 
```
outputs:
  default:
    type: elasticsearch
    hosts: '<your-elasticsearch-endpoint>:<port>'
    api_key: 'your-api-key'
inputs:
  - id: your-log-id
    type: filestream
    streams:
      - id: your-log-stream-id
        data_stream:
          dataset: example
        paths:
          - /var/log/your-logs.log
```
