### ISSUE TITLE
Add concrete steps on how to build a custom collector that contains all the components required

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#4126]
Add steps on building a custom collector on [the OTel docs](https://github.com/elastic/opentelemetry/blob/main/docs/configure-upstream-collector.md)

> we need more concrete steps on how exactly to build a custom collector that contains all the components required. Could we maybe even provide the config file for ocb? @ishleenk17 could you help with the concrete steps here?

**Comment by ishleenk17** [comment]
## Steps to Build a Custom Collector

### 1. Install OpenTelemetry Collector Builder
First, you need to install the OpenTelemetry Collector Builder if you haven't already by using the below command:

`go install go.opentelemetry.io/collector/cmd/builder@latest
`

### 2. Create a New Collector Configuration
Create a builder configuration file (e.g., builder-config.yml) that defines your custom collector. This file specifies the components (receivers, exporters, processors, and extensions) that your custom collector will include.

Example builder-config.yml:

``` yaml
dist:
  name: "custom-otel-collector"
  description: "Custom OpenTelemetry Collector"
  output_path: "./build"

receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.103.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.103.0"

processors:
  - gomod:  "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.103.0"
  - gomod:  "github.com/elastic/opentelemetry-collector-components/processor/elasticinframetricsprocessor v0.5.1"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.103.0"
  
exporters:
  - gomod: "go.opentelemetry.io/collector/exporter/otlphttpexporter v0.103.0"
  - gomod: "go.opentelemetry.io/collector/exporter/loggingexporter v0.103.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.103.0"

```

In this example config, we can include all the relevant receivers, processors, exporters required by the collector.


### 3. Build the Collector
Use the ocb tool to build your custom collector using the configuration file:

`builder --config builder-config.yml`

This command generates a new collector in the specified output path (e.g., ./build). The generated collector will include only the components you specified in the configuration file.
